include: package:leancode_lint/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - lib/common/l10n/app_localizations_en.dart
    - lib/common/l10n/app_localizations_pl.dart
    - lib/common/l10n/app_localizations.dart
    - '**/*.g.dart'