name: knam
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  dio: ^5.3.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_comms: ^1.1.0
  flutter_hooks: ^0.20.3
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.18+2
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  intl: ^0.18.1
  leancode_lint: ^7.0.0+1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  url_strategy: ^0.2.0

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.7
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.3.4

flutter:
  uses-material-design: true
